doc: Add build an end to end solution with GN
TheThingsIndustries/lorawan-stack-docs pull request #1035
Opened 2023-02-05 13:02 UTC by pradeeka7

#### Summary

This project shows how to build an end-to-end solution with The Things Stack to control the Kuando Busylight with the Generic Node Sensor Edition.

#### Screenshots

![image](https://user-images.githubusercontent.com/36432168/216819220-6abcc401-d810-4473-8739-851468f5466e.png)

#### Changes

- New documentation 
- ...

#### Notes for Reviewers

- @benolayinka please review.
- Some screenshots need to be replaced since I can't reproduce them.

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [X] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [X] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [X] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2023-02-22 19:28 UTC, azerimaker approved these changes
Look good, @pradeeka7 .

2023-02-25 17:35 UTC, nejraselimovic requested changes
I'm also not sure we want to do this. Where did you get the idea for writing this article? Did you discuss this with someone or? Because I don't think we want to have a million articles on how to use different devices in our documentation. We had a section on TTN forum for writing success stories, so this could be easily placed there, and you could turn this article into section about onboarding GNSE instead. GNSE is our product after all, and we don't have it documented as far as I can see.

This article is awesome, but I just don't think its place is in our product documentation. There is a lot of overhead content like adding app, adding device, adding gateway, adding integration, etc. and that's the content we already have extensively documented.

2023-02-25 17:35 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +Generic Node Sensor Edition is a hardware platform that simplifies building LoRaWAN® end-devices for various use cases. It provides a fast development lifecycle from concept to production with its re
Please link the documentation to Generic Node somewhere

2023-02-25 17:35 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +An end device can be added to {{% tts %}} through [manual onboarding](https://www.thethingsindustries.com/docs/devices/adding-devices/#manually-registering-an-end-device), [device repository](https:/
Make this short and just link Adding devices

2023-02-25 17:35 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +In this project, we will add the Generic Node to {{% tts %}} by scanning its QR code. The QR code for claiming the Generic Node is located on the back of its enclosure. For complete steps on how to c
Add GNSE abbreviation at the beginning and use it in the rest of the section

2023-02-25 17:35 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +In this project, we will add the Generic Node to {{% tts %}} by scanning its QR code. The QR code for claiming the Generic Node is located on the back of its enclosure. For complete steps on how to c
```suggestion
In this section, we will add GNSE to {{% tts %}} by scanning its QR code. The QR code for claiming the Generic Node is located on the back of its enclosure. For complete steps on how to claim a device using a QR code, please refer to the instructions available [here](https://www.thethingsindustries.com/docs/devices/adding-devices/#onboarding-devices-using-qr-codes).
```

2023-02-25 17:35 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +- Select the uplink message. You can see the detailed view of your message in the **Event details** window. Scroll down and see what’s in the **frm_payload** (frame payload) field. The payload is enc
Remove bullets please

2023-02-25 17:35 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +- Select the uplink message. You can see the detailed view of your message in the **Event details** window. Scroll down and see what’s in the **frm_payload** (frame payload) field. The payload is enc
Payload is maybe not comprehensible to every human, but you can't say it's not useful. Please reword this and link payload formatting section

2023-02-26 12:33 UTC, pradeeka7 commented
> I'm also not sure we want to do this. Where did you get the idea for writing this article? Did you discuss this with someone or? Because I don't think we want to have a million articles on how to use different devices in our documentation. I think you should turn this article into section about onboarding GNSE instead. GNSE is our product after all, and we don't have it documented as far as I can see. I added some comments for improving that part, but I think the rest should be removed and placed on TTN forum under [success stories](https://www.thethingsnetwork.org/forum/c/use-cases/14).
> 
> This article is awesome, but I just don't think its place is in our product documentation. There is a lot of overhead content like adding app, adding device, adding gateway, adding integration, etc. and that's the content we already have extensively documented.

I wrote this document as requested by @wienke. Anastasia, @kschiffer, and @benolayinka are also aware of it. I have all the conversations in my email.

2023-02-26 16:10 UTC, nejraselimovic commented
> > I'm also not sure we want to do this. Where did you get the idea for writing this article? Did you discuss this with someone or? Because I don't think we want to have a million articles on how to use different devices in our documentation. I think you should turn this article into section about onboarding GNSE instead. GNSE is our product after all, and we don't have it documented as far as I can see. I added some comments for improving that part, but I think the rest should be removed and placed on TTN forum under [success stories](https://www.thethingsnetwork.org/forum/c/use-cases/14).
> > This article is awesome, but I just don't think its place is in our product documentation. There is a lot of overhead content like adding app, adding device, adding gateway, adding integration, etc. and that's the content we already have extensively documented.
> 
> I wrote this document as requested by @wienke. Anastasia, @kschiffer, and @benolayinka are also aware of it. I have all the conversations in my email.

Ok then, if it's requested then that's fine I guess. I still think there is a lot of overhead in this article. My advise would be to make more use of the content we already have (adding apps, registering gateways and devices, creating webhooks, etc.). For example, I think there's no need to document steps for adding a TTIG when we already have a dedicated guide for it https://www.thethingsindustries.com/docs/gateways/models/thethingsindoorgateway/.

But then again, I don't know the context of your discussion about this, so can you please forward me those emails so I can check it out?

2023-02-27 17:23 UTC, benolayinka commented
Yep this was Wienke's content idea. Like @nejraselimovic says, lets link to as much documentation as possible rather than rewriting everything from scratch, and then this can be an end to end example in getting started.

2023-03-04 11:30 UTC, pradeeka7 commented
> Yep this was Wienke's content idea. Like @nejraselimovic says, lets link to as much documentation as possible rather than rewriting everything from scratch, and then this can be an end to end example in getting started.

@nejraselimovic I am working on linking instructions to the existing content.

2023-03-05 11:31 UTC, nejraselimovic commented
> > Yep this was Wienke's content idea. Like @nejraselimovic says, lets link to as much documentation as possible rather than rewriting everything from scratch, and then this can be an end to end example in getting started.
> 
> @nejraselimovic I am working on linking instructions to the existing content.

Great! Tag me for another review when done

2023-04-04 18:40 UTC, nejraselimovic requested changes
Some of these screenshots look pretty bad. If you took them, please refer to the contributing guidelines [here](https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/CONTRIBUTING.md) and take screenshots as shown there.

2023-04-04 18:40 UTC, nejraselimovic commented on doc/content/getting-started/guides/_index.md
> +You can access comprehensive tutorials for building diverse applications using {{% tts %}} here.
```suggestion
Learn how to build diverse applications using {{% tts %}}.
```

2023-04-04 18:40 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +title: "Building an End-to-End LoRaWAN Application with The Things Stack"
```suggestion
title: "Build an Application using Generic Node Sensor Edition and Kuando Busylight"
```

2023-04-04 18:40 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +# Registering The Things Indoor Gateway
```suggestion
## Registering The Things Indoor Gateway
```

2023-04-04 18:40 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +# Registering The Things Indoor Gateway
add one more hash, otherwise these don't show up on the right navigation bar. this goes for the whole doc

2023-04-04 18:40 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +Register The Things Indoor Gateway with {{% tts %}} by following the instructions on this [page](/gateways/models/thethingsindoorgateway/). Once registered, your gateway will be ready to receive upli
```suggestion
Register The Things Indoor Gateway with {{% tts %}} by following [these instructions]({{< "/gateways/models/thethingsindoorgateway" >}}). Once registered, your gateway will be ready to receive uplinks and forward downlinks.
```

2023-04-04 18:40 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +Register The Things Indoor Gateway with {{% tts %}} by following the instructions on this [page](/gateways/models/thethingsindoorgateway/). Once registered, your gateway will be ready to receive upli
Are you sure that putting the link without {{< >}} works in production? I'm not sure

2023-04-04 18:40 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +Create a new application with {{% tts %}} by following the instructions on this [page](/integrations/adding-applications/).
```suggestion
Create a new application with {{% tts %}} by following [these instructions](/integrations/adding-applications/).
```

2023-04-04 18:40 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +In this section, we will show how to build an end-to-end solution with [{{% tts %}}](/getting-started/what-is-tts/) to control the [Kuando Busylight](https://busylight.com/busylight-iot/) with the [G
```suggestion
In this section, we will show how to build an end-to-end solution with [{{% tts %}}](/getting-started/what-is-tts/) to control the [Kuando Busylight](https://busylight.com/busylight-iot/) with the [Generic Node Sensor Edition](https://www.thethingsshop.com/products/generic-node-sensor-edition) (GNSE). 
```

2023-04-04 18:40 UTC, nejraselimovic commented on doc/content/getting-started/guides/build-an-end-to-end-solution-gn/_index.md
> +# Adding Generic Node SE
why Generic Node SE when you introduced GNSE in the beginning?

2023-04-05 01:19 UTC, pradeeka7 commented
> Some of these screenshots look pretty bad. If you took them, please refer to the contributing guidelines [here](https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/CONTRIBUTING.md) and take screenshots as shown there.

Could you please hold this pull request until I generate the screenshots? I have taken them from Kevin's video. It is difficult for me to generate some images, including the charts, because I don't have a Kuando Busy Light.

2023-04-08 18:18 UTC, nejraselimovic commented
> > Some of these screenshots look pretty bad. If you took them, please refer to the contributing guidelines [here](https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/CONTRIBUTING.md) and take screenshots as shown there.
> 
> Could you please **HOLD** this pull request until I generate the screenshots? I have taken them from Kevin's video. It is difficult for me to generate some images, including the charts, because I don't have a Kuando Busy Light.

That's fine, you can take them from video, but please crop them nicely. We don't want to see the browser URL bar, we don't want to have a half of TTS logo (if it cannot be fully visible, just crop it out), we don't want to see a half of the navigation bar, etc.

2023-05-09 20:04 UTC, nejraselimovic commented
> > > Some of these screenshots look pretty bad. If you took them, please refer to the contributing guidelines [here](https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/CONTRIBUTING.md) and take screenshots as shown there.
> > 
> > 
> > Could you please **HOLD** this pull request until I generate the screenshots? I have taken them from Kevin's video. It is difficult for me to generate some images, including the charts, because I don't have a Kuando Busy Light.
> 
> That's fine, you can take them from video, but please crop them nicely. We don't want to see the browser URL bar, we don't want to have a half of TTS logo (if it cannot be fully visible, just crop it out), we don't want to see a half of the navigation bar, etc.

Hey @pradeeka7, what is the status here? Can we finalize it?

2023-05-10 05:10 UTC, pradeeka7 commented
> Hey @pradeeka7, what is the status here? Can we finalize it?

I have just updated the screenshots. These are the highest quality images I could capture from YouTube.

2023-05-13 21:01 UTC, merged