doc: Add Generic Node Sensor Edition
TheThingsIndustries/lorawan-stack-docs pull request #1037
Opened 2023-02-10 07:51 UTC by pradeeka7

#### Summary

Document the process of registering the Generic Node Sensor Edition with The Things Stack. Link to the issue: https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/988

#### Screenshots

![image](https://user-images.githubusercontent.com/36432168/218031508-2c6e0ab9-ef6f-417e-8548-195aad25f6cf.png)

#### Changes

- New document
- ...

#### Notes for Reviewers

@nejraselimovic @benolayinka Can you review?
I am unable to provide REAL screen captures for certain steps (ie. screenshots with JoinEUI all zeros etc) due to the absence of a QR code on my Generic Node. 
...

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [X] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [X] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [X] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2023-02-19 17:16 UTC, nejraselimovic requested changes

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +- The camera will start up and be ready to scan the QR code. To begin, bring the QR code for your device close to the camera.
```suggestion
- The camera will start up and be ready to scan the QR code. To scan the device, bring the QR code close to the camera.
```

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +- A window with information from the QR code should appear on your screen, displaying the **Claim authentication code**, **JoinEUI**, **DevEUI**, and **Brand** for your device. If the data displayed
```suggestion
- A window with information scanned from the QR code (like **Claim authentication code**, **JoinEUI**, **DevEUI** and **Brand**) should appear on your screen. If the data displayed is correct, select the **Apply** button.
```

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +- Sign in to [{{% tts %}}](/getting-started/).
Also, remove `-` bullets from this and following steps.

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +## Using the LoRaWAN Device Repository
```suggestion
### Using the LoRaWAN Device Repository
```

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +## Manually
```suggestion
### Manual Registration
```

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +The [Device repository](https://github.com/TheThingsNetwork/lorawan-devices) comprises over 600 end-device profiles, including the Generic Node Sensor Edition, which requires less information for reg
```suggestion
The [LoRaWAN Device Repository](https://github.com/TheThingsNetwork/lorawan-devices) comprises over 600 end-device profiles, including the Generic Node Sensor Edition, which requires less information for registration with {{% tts %}}.
```

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +- In the **End device type** section, under **Input Method** select **Select the end device in the LoRaWAN device repository**. Then select/enter the following settings:
Remove the bullet

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +  - **Frequency plan**: choose the frequency plan appropriate for your region/country, for example, if you are live in Europe, choose **Europe 863-870 MHz (SF9 for RX2 - recommended)**.
For selected values use **bold** and for entered values use `highlight`

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +- Select the **Register end device** button.
Remove bullet

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +The device is now registered and you will be redirected to the **overview** page of the device.
```suggestion
The device is now registered and you will be redirected to the **Overview** page of the device.
```

2023-02-19 17:16 UTC, nejraselimovic commented on doc/content/devices/generic-node-se/_index.md
> +The device is now registered and you will be redirected to the **overview** page of the device.
Same comments as for the section above

2023-02-21 00:40 UTC, pradeeka7 commented on doc/content/devices/generic-node-se/_index.md
> +The Generic Node Sensor Edition comes with a pre-loaded application called [vanilla](https://www.genericnode.com/docs/applications/se-vanilla/) that showcases the device's functions and capabilities.
Yes, indeed.

2023-02-21 00:41 UTC, pradeeka7 commented on doc/content/devices/generic-node-se/_index.md
> +This section will provide guidance on how to begin using [Generic Node Sensor Edition](https://www.genericnode.com/docs/sensor-edition/) on {{% tts %}}.
Will do.

2023-02-25 16:22 UTC, nejraselimovic approved these changes

2023-02-25 16:22 UTC, merged

2023-02-25 16:22 UTC, nejraselimovic commented
Nice job @pradeeka7!