doc: Remove v2-related content
TheThingsIndustries/lorawan-stack-docs pull request #1081
Opened 2023-04-16 10:56 UTC by nejraselimovic

#### Summary
Closes #1053 
References #1076

#### Checklist
- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2023-04-17 14:10 UTC, johanstokking approved these changes

2023-04-21 11:14 UTC, adriansmares approved these changes

2023-04-21 11:27 UTC, KrishnaIyer requested changes
@nejraselimovic: We have some customers who still need the information on migrating from v2 to v3. Please retain the relevant content.
We can remove TTN related content though, the takeout tool.

2023-04-27 17:38 UTC, nejraselimovic commented
> @nejraselimovic: We have some customers who still need the information on migrating from v2 to v3. Please retain the relevant content. We can remove TTN related content though, the takeout tool.

Are you sure? Because I asked that a while ago and RIsh said it's safe to remove this https://thethingsindustries.slack.com/archives/C013TFXG3GC/p1672009274437209

2023-05-13 19:06 UTC, closed without merging