Create new_in_version Front Matter
TheThingsIndustries/lorawan-stack-docs pull request #109
Opened 2020-11-18 16:39 UTC by benolayinka

#### Summary

Add Front Matter to mark entire sections as "New in Version."

Looks like:
<img width="467" alt="Screenshot 2020-11-18 at 17 07 44" src="https://user-images.githubusercontent.com/6963436/99559018-9e3c1a80-29c4-11eb-8d87-86e15c89e479.png">

And automatically marks the title on the content page:
<img width="630" alt="Screenshot 2020-11-18 at 17 09 39" src="https://user-images.githubusercontent.com/6963436/99559045-a85e1900-29c4-11eb-844c-beeaca744d8a.png">

Only problem is that it sometimes wraps
<img width="715" alt="Screenshot 2020-11-18 at 17 29 12" src="https://user-images.githubusercontent.com/6963436/99559118-b7dd6200-29c4-11eb-9be3-e76d5b4fb664.png">

Currently styled exactly like inline distributions (distributions styling will change soon with logos)
<img width="748" alt="Screenshot 2020-11-18 at 17 31 05" src="https://user-images.githubusercontent.com/6963436/99559199-cd528c00-29c4-11eb-9c5d-1e1f82e5e196.png">

@pierrephz @kschiffer any quick feedback?

#### Changes

- Add Front Matter
- Add documentation
- Clean up existing tags

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2020-11-19 08:12 UTC, htdvisser approved these changes
That little change in my code-owned `doc/content/reference/configuration/identity-server.md` is ok.

2020-11-19 08:28 UTC, nejraselimovic approved these changes

2020-11-19 09:54 UTC, johanstokking approved these changes

2020-11-19 09:54 UTC, johanstokking commented
@benolayinka always set an assignee and milestone

2020-11-19 12:35 UTC, kschiffer commented
I'll leave this to @pierrephz

2020-11-20 14:45 UTC, pierrephz requested changes
Since we decided to go with colors for different deployments, let's use them in this case:

![image](https://user-images.githubusercontent.com/26456318/99812316-97d5ac00-2b46-11eb-9b82-5572958787ca.png)

let's have some kind of label below titles (see mockups) to specify which deployment is involved.
it's fine to have only "News in 3.10" superscript, but don't use ITC Avant Garde here (see mockups)

cc @benolayinka

2020-11-23 15:57 UTC, benolayinka commented
> Since we decided to go with colors for different deployments, let's use them in this case:
> 
> ![image](https://user-images.githubusercontent.com/26456318/99812316-97d5ac00-2b46-11eb-9b82-5572958787ca.png)
> 
> let's have some kind of label below titles (see mockups) to specify which deployment is involved.
> it's fine to have only "News in 3.10" superscript, but don't use ITC Avant Garde here (see mockups)
> 
> cc @benolayinka

Sounds good. The dist icons is another PR

2020-11-23 16:20 UTC, pierrephz approved these changes

2020-11-24 10:47 UTC, adriansmares approved these changes

2020-11-24 10:51 UTC, merged