doc: Add subscription process of TTSC via AWS Marketplace
TheThingsIndustries/lorawan-stack-docs pull request #1305
Opened 2024-04-08 15:23 UTC by Siva-7482

#### Summary

Process for subscribing to The Things Stack Cloud via AWS Marketplace.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/430

#### Screenshots

...

#### Changes

- Added a new section with the process of subscribing to The Things Stack Cloud via AWS Marketplace.
- Added the relevant screenshots.

#### Notes for Reviewers

@KrishnaIyer, please review.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2024-04-09 08:45 UTC, adriansmares reviewed
This LGTM but these `:Zone.Identifier` files shouldn't be committed.

2024-04-10 09:41 UTC, Siva-7482 commented
Sure, @adriansmares. The zone identifier files were removed and updated the PR.

2024-04-10 12:43 UTC, adriansmares approved these changes

2024-04-10 19:26 UTC, nejraselimovic requested changes

2024-04-10 19:26 UTC, nejraselimovic commented on doc/content/the-things-stack/cloud/subscribe-tts-via-aws-marketplace/_index.md
> +Navigate to [The Things Stack Cloud for LoRaWAN](https://aws.amazon.com/marketplace/pp/prodview-djx65iyt6w5cy) in AWS Marketplace.
```suggestion
Navigate to [{{% tts %}} Cloud for LoRaWAN](https://aws.amazon.com/marketplace/pp/prodview-djx65iyt6w5cy) in AWS Marketplace.
```

2024-04-10 19:26 UTC, nejraselimovic commented on doc/content/the-things-stack/cloud/subscribe-tts-via-aws-marketplace/_index.md
> +{{< figure src="configure-account.png" alt="Configure Account" >}}
Can you please retake screenshots in a way described in [CONTRIBUTING doc](https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/CONTRIBUTING.md)? This one looks off, and the `setup-product.png` above is unequally cropped

2024-04-21 19:47 UTC, nejraselimovic approved these changes

2024-04-21 19:47 UTC, merged