Create distribution badges to mark features specific to a distribution
TheThingsIndustries/lorawan-stack-docs pull request #134
Opened 2020-12-01 14:09 UTC by benolayinka

#### Summary

Add badges for the different The Things Stack distributions. Looks like this:

<img width="741" alt="Screenshot 2020-12-01 at 15 03 55" src="https://user-images.githubusercontent.com/6963436/100750770-cb39f580-33e6-11eb-9561-cbd337b65d7b.png">

<img width="780" alt="Screenshot 2020-12-01 at 15 03 01" src="https://user-images.githubusercontent.com/6963436/100750793-d2f99a00-33e6-11eb-833d-ef572099aa62.png">

#### Notes for Reviewers

@pierrephz, PR needs a TTN frame. Is this a colored square or the TTN logo? @johanstokking ?

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2020-12-02 08:55 UTC, htdvisser commented on doc/themes/the-things-stack/layouts/partials/distribution-badges.html
> +		    <span class="has-text-weight-bold">{{ . }}</span>
- Inconsistent use of tabs and spaces
- Use `relURL` (like we do in check-icon: `src="{{ "img/check.svg" | relURL }}"`)

2020-12-02 08:55 UTC, htdvisser commented on doc/themes/the-things-stack/layouts/_default/single.html
> +	</p>
Inconsistent use of tabs and spaces

2020-12-02 08:55 UTC, htdvisser commented on doc/themes/the-things-stack/layouts/_default/list.html
> +	</p>
Inconsistent use of tabs and spaces

2020-12-02 08:55 UTC, htdvisser commented on doc/themes/the-things-stack/assets/css/theme.scss
> +
I'm fine with removing this comment and just importing the entire library

2020-12-02 10:04 UTC, pierrephz requested changes
be careful with the badges
- don't use ITC avant-garde here

![image](https://user-images.githubusercontent.com/26456318/100857001-68029e80-348c-11eb-854c-1ac994f2ccea.png)

- make sure the balance of the badge is right (icon + text centered in the frame)

![image](https://user-images.githubusercontent.com/26456318/100857180-ae57fd80-348c-11eb-9a16-c525e45291a5.png)

- make a bit more space between the icon and the text in the badge (see below)

<img width="1405" alt="Screenshot 2020-12-02 at 11 03 45" src="https://user-images.githubusercontent.com/26456318/100858289-165b1380-348e-11eb-9c1d-bef31ecf2d46.png">

2020-12-02 10:17 UTC, pierrephz commented
> I also left the inline distribution shortcode untouched because sometimes it has to fit in tiny tables, but @pierrephz maybe you can think of an aesthetic way to integrate it here?:

regarding this, I am thinking about an. "information" label that you can hover to get the info (see screenshot below):

![image](https://user-images.githubusercontent.com/26456318/100859722-db59df80-348f-11eb-9b03-1790c65a0b0a.png)

2020-12-15 16:30 UTC, benolayinka commented
> > I also left the inline distribution shortcode untouched because sometimes it has to fit in tiny tables, but @pierrephz maybe you can think of an aesthetic way to integrate it here?:
> 
> regarding this, I am thinking about an "information" label that you can hover to get the info (see screenshot below):
> 
> ![image](https://user-images.githubusercontent.com/26456318/100859722-db59df80-348f-11eb-9b03-1790c65a0b0a.png)

I like this idea, but maybe we use a tiny colored stack of icons instead of the bubble? @htdvisser also suggested wrapping sections to fix https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/139

2020-12-28 16:17 UTC, benolayinka commented
@pierrephz @kschiffer how about something like this for inline? we could also even minimize all the badges

<img width="561" alt="Screenshot 2020-12-28 at 17 16 04" src="https://user-images.githubusercontent.com/6963436/103228232-927f3480-4930-11eb-8b73-7ad7e56215d4.png">

2020-12-28 16:32 UTC, benolayinka commented
and for the badges @pierrephz ? or we can just change everything to the stacked icons

<img width="547" alt="Screenshot 2020-12-28 at 17 31 05" src="https://user-images.githubusercontent.com/6963436/103229080-a035b980-4932-11eb-87bf-9e3309342201.png">

2020-12-29 09:33 UTC, kschiffer commented
> @pierrephz @kschiffer how about something like this for inline? we could also even minimize all the badges
> 
> ![Screenshot 2020-12-28 at 17 16 04](https://user-images.githubusercontent.com/6963436/103228232-927f3480-4930-11eb-8b73-7ad7e56215d4.png)

Just the (stacked) icons is too implicit. I think this only works in conjunction with a descriptive label, e.g. `All deployment models`.

2020-12-29 11:52 UTC, pierrephz commented
Yea could be
What is the purpose? save some space?

> Actually, I think for inline, this can work, if it shows the tooltip on hover. I still think the stacked icon needs to be a bit clearer though.

yes, should be a bit larger, and more space in-between if we go for this

2020-12-29 11:57 UTC, benolayinka commented
> Yea could be
> What is the purpose? save some space?
> 
> > Actually, I think for inline, this can work, if it shows the tooltip on hover. I still think the stacked icon needs to be a bit clearer though.
> 
> yes, should be a bit larger, and more space in-between if we go for this

Yep, especially for places with no space. It is also much less intrusive.

<img width="806" alt="Screenshot 2020-12-29 at 12 56 27" src="https://user-images.githubusercontent.com/6963436/103282206-581ba300-49d5-11eb-8535-c8508bc10cfd.png">

2020-12-29 18:46 UTC, benolayinka commented
ok @pierrephz here's what I have today:

On cards:
<img width="403" alt="Screenshot 2020-12-29 at 19 43 33" src="https://user-images.githubusercontent.com/6963436/103306592-34c11a00-4a0e-11eb-9b79-5945bb2fdd19.png">

Inside page and inline:
<img width="411" alt="Screenshot 2020-12-29 at 19 43 49" src="https://user-images.githubusercontent.com/6963436/103306611-40144580-4a0e-11eb-9767-0bdefe65276d.png">

@kschiffer the frustrating issue i'm encountering is that the image span isn't lining up with the text. There's no up or down margin or anything on the spans, I can't understand why they are moving vertically?

<img width="476" alt="Screenshot 2020-12-29 at 19 38 50" src="https://user-images.githubusercontent.com/6963436/103306667-6df98a00-4a0e-11eb-9367-2f78797365da.png">

<img width="348" alt="Screenshot 2020-12-29 at 19 38 11" src="https://user-images.githubusercontent.com/6963436/103306678-75b92e80-4a0e-11eb-945f-48b67d3a9aa4.png">

2021-01-13 10:58 UTC, benolayinka commented
Decided to go with the stacked icons because it's clean, simple, fits everywhere, and is nearly fixed size. @pierrephz please take a look. Also, we need an icon for The Things Network. Maybe a little cloud or something?

2021-01-13 14:13 UTC, pierrephz approved these changes
@benolayinka that works
find here the cloud icon for ttn: 
[ttn.svg.zip](https://github.com/TheThingsIndustries/lorawan-stack-docs/files/5809071/ttn.svg.zip)

2021-01-14 09:52 UTC, nejraselimovic approved these changes
Looks great, good job! Here's some remarks:

- I had to change `@import "@creativebulma/bulma-tooltip/dist/bulma-tooltip.min"` to `@import "@creativebulma/bulma-tooltip/dist/bulma-tooltip.min.css"` in order to make this work
- I'm not seeing tooltip on hover

2021-01-15 11:54 UTC, kschiffer requested changes
> Looks great, good job! Here are some remarks:
> 
> *   I had to change `@import "@creativebulma/bulma-tooltip/dist/bulma-tooltip.min"` to `@import "@creativebulma/bulma-tooltip/dist/bulma-tooltip.min.css"` in order to make this work
> *   I'm not seeing tooltip on hover

Same here.

2021-02-03 12:06 UTC, benolayinka commented
> Looks great, good job! Here are some remarks:
> 
> * I had to change `@import "@creativebulma/bulma-tooltip/dist/bulma-tooltip.min"` to `@import "@creativebulma/bulma-tooltip/dist/bulma-tooltip.min.css"` in order to make this work
> * I'm not seeing tooltip on hover

Should be fixed now, the I added the `bulma-tooltip` package with npm when I should have used yarn, so it wasn't in `yarn.lock` and `make deps` didn't install it for you.

2021-02-03 12:08 UTC, benolayinka commented
> @benolayinka that works
> find here the cloud icon for ttn:
> [ttn.svg.zip](https://github.com/TheThingsIndustries/lorawan-stack-docs/files/5809071/ttn.svg.zip)

With the ttn frame it looks like this:

<img width="634" alt="Bildschirmfoto 2021-02-03 um 13 59 46" src="https://user-images.githubusercontent.com/6963436/106745022-3d1dfd80-6629-11eb-96f0-8fe8b50d723c.png">

Is that okay or we do something else?

2021-02-08 11:44 UTC, kschiffer approved these changes

2021-02-09 07:55 UTC, neoaggelos approved these changes

2021-02-09 10:11 UTC, adriansmares approved these changes

2021-02-09 10:25 UTC, johanstokking approved these changes
Code owned files LGTM

2021-02-09 11:53 UTC, merged