doc: Fix links to files in lorawan-stack repository
TheThingsIndustries/lorawan-stack-docs pull request #137
Opened 2020-12-02 13:31 UTC by htdvisser

#### Summary

Closes #113

#### Changes

- Deleted unused `repo` shortcode
- Renamed `repo-file-url` to `tts-repo-file-url` and make it link to current minor branch of https://github.com/TheThingsNetwork/lorawan-stack.
- Fixed documentation pages that linked to `default` branch

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2020-12-02 17:35 UTC, kschiffer approved these changes

2020-12-03 09:33 UTC, pierrephz approved these changes

2020-12-03 12:23 UTC, johanstokking requested changes

2020-12-03 12:23 UTC, johanstokking commented on doc/config/_default/config.toml
> +  tts_github_repository = "https://github.com/TheThingsIndustries/lorawan-stack"
This should likely be the open source repo

2020-12-04 08:17 UTC, johanstokking approved these changes

2020-12-04 08:19 UTC, merged