Improve docs navigation
TheThingsIndustries/lorawan-stack-docs pull request #223
Opened 2021-02-08 13:20 UTC by benolayinka

#### Summary

First draft of the new docs nav. Looks like this:

![localhost_1313_getting-started_installation_(Laptop with HiDPI screen) (1)](https://user-images.githubusercontent.com/6963436/107222881-265b1a80-6a1e-11eb-86d8-8f6256ec2498.png)

TODO:
- We may have to remove tabs in some places, because any headings within tabs shortcodes won't appear in the right hand navigation. Since we have right hand navigation, we can use headings and allow users to skip to the correct section (have a console heading and a cli heading).
- Make maximum depth 2 (fix cloud integrations) - let's go through and condense instructions which need to be followed in order in to one page, the cloud integrations are a perfect example. I've done it for Akenza as an example. @nejraselimovic 
- Add text in overviews, since these pages are now visible (no more cards). @nejraselimovic 
- Can't have shortcodes in headings - we have to think of another solution for the new-in-version, deprecated, distribution only shortcodes because these break the right hand navigation links
- Clean up css (ill do this)
- Make headings more descriptive (localhost -> Installing The Things Stack on Localhost) @nejraselimovic 

#### Screenshots

### Remove or fix tabs.
Here its fine because the heading is outside the tab (the heading still appears in the TOC on the right:
<img width="694" alt="Bildschirmfoto 2021-02-08 um 15 05 21" src="https://user-images.githubusercontent.com/6963436/107223853-5bb43800-6a1f-11eb-88b5-8a526dc25a72.png">

Here the heading is INSIDE the tab so it doesn't appear in the TOC (see the TOC on the right is empty)
<img width="921" alt="Bildschirmfoto 2021-02-08 um 15 05 53" src="https://user-images.githubusercontent.com/6963436/107223978-830b0500-6a1f-11eb-9a56-a91f24c3ef39.png">

### Make maximum depth 2 (fix cloud integrations)
Since we have right hand nav, we can combine the integration subpages in to one page, to be followed consecutively (did it already for Akenza):
![localhost_1313_integrations_cloud-integrations_akenza-core_(Laptop with HiDPI screen)](https://user-images.githubusercontent.com/6963436/107224713-7804a480-6a20-11eb-85ca-b9ccbc78da45.png)

### Add text in overviews
We should put something in these docs:
![localhost_1313_getting-started_(Laptop with HiDPI screen) (1)](https://user-images.githubusercontent.com/6963436/107224805-9a96bd80-6a20-11eb-80dd-2bd5a4e3e5e1.png)

### Cant have shortcodes in headings
Using shortcodes in headings breaks the table of contents. We need to find another solution here
![localhost_1313_getting-started_installation_configuration_(Laptop with HiDPI screen)](https://user-images.githubusercontent.com/6963436/107224897-c0bc5d80-6a20-11eb-9245-056d21896187.png)

### Make headings more descriptive
Localhost -> Installing TTS on localhost, for example, to make the TOC more clear
![localhost_1313_getting-started_installation_configuration_(Laptop with HiDPI screen) (1)](https://user-images.githubusercontent.com/6963436/107225080-0547f900-6a21-11eb-99a7-d3f2b57a565e.png)

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2021-02-08 13:21 UTC, benolayinka commented
@nejraselimovic i tagged you in a few TODOs i could use your help on 👏🏽

2021-02-10 12:15 UTC, johanstokking reviewed
Looks great. Please request review when ready.

I'm okay with having rather more than less items in the sidebar. I would propose making it more condensed and smaller font size. The biggest problem I have today that I cannot find things in the docs, and so a sidebar with a ToC is very helpful.

2021-02-18 14:54 UTC, johanstokking commented
Small issue with the header; the banner isn't the full width:

<img width="1917" alt="Screenshot 2021-02-18 at 15 54 14" src="https://user-images.githubusercontent.com/13334001/108374749-9416fb80-7201-11eb-8fa3-0df79cb9866f.png">

2021-02-23 09:45 UTC, benolayinka commented
> * The banner needs some tweaking. Let's make sure the banner keeps working because we probably need it in the future for something
> * I find the differences in the font size a bit too much; the text in the sidebar is quite small, compared to the body and headings
> * Rename title **Cloud** to **The Things Stack Cloud** (http://localhost:1313/getting-started/cloud-hosted/)
> 
> I didn't review the code (yet), let me know if that is needed

Good catch - fixed the banner, bumped up the font size (to 0.95 of main) and renamed Cloud to TTS Cloud.

2021-02-25 09:43 UTC, pierrephz commented
@benolayinka this is a very nice improvement

I have now two things to say:

- let's use a third blue (#E5ECFF) to highlight the current option selected on the nav (see screenshot). Having only a strong blue and white is becoming a bit too agressif.

<img width="1552" alt="Screenshot 2021-02-25 at 10 39 36" src="https://user-images.githubusercontent.com/26456318/109134013-e1412300-7755-11eb-857e-307d8ba9a591.png">

- from Johan's screenshot, it seems like the nav is not fixed. It should stay fixed on the left while you scroll, like that it's always usable even if you are at the bottom of the page. You don't have to scroll up to find the nav back

2021-02-25 09:44 UTC, pierrephz requested changes
See my comment above

2021-02-25 10:42 UTC, kschiffer reviewed
I'm currently unable to run the dev server due to:
```
go run -tags extended github.com/gohugoio/hugo server -s doc --environment gh-pages
../../go/pkg/mod/github.com/gohugoio/hugo@v0.81.0/tpl/internal/go_templates/texttemplate/helper.go:11:2: package io/fs is not in GOROOT (/usr/local/Cellar/go/1.15.6/libexec/src/io/fs)
make: *** [server] Error 1
```
So I cannot finish the review.

2021-02-25 10:42 UTC, kschiffer commented on doc/assets/css/sidebar/sidebar.scss
> +    align-self: flex-start; /* Fix for sticky in flex */
```suggestion
    align-self: flex-start; // Fix for sticky in flex
```

Nit

2021-02-25 10:42 UTC, kschiffer commented on doc/assets/css/theme.scss
> +// Node_modules mounted to css/vendor and js/vendor in config.toml
```suggestion
// `node_modules` mounted to css/vendor and js/vendor in config.toml
```

Nit

2021-02-25 10:42 UTC, kschiffer commented on doc/layouts/_default/list.html
> +{{ partial "feedback" . }}
Please decide on one indentation style, it's currently not consistent. I'd suggest 2 spaces.

2021-02-25 13:16 UTC, htdvisser reviewed
Maybe add CODEOWNERS for `doc/assets/css`, otherwise those files don't get reviewed.

2021-03-01 11:34 UTC, benolayinka commented
> See my comment above

The left scrollbar is fixed, it's just that when the banner is showing it messes up the vertical padding on the body that is built in to bulma. This is hard to fix, because it's done with variables in bulma's css, and the banner is toggled in javascript. I'm going to leave this bug in to live with for now. Dismissing the banner fixes it.

2021-03-01 11:37 UTC, nejraselimovic approved these changes

2021-03-03 10:33 UTC, benolayinka commented
@johanstokking i went back to small font for the left and right, mimicking the styling here -> https://doks.netlify.app/docs/prologue/introduction/

It looks much cleaner as the left side menu expands, preventing the text from wrapping. Give it one last look and see what you think.

@kschiffer do you still have the error preventing you from running the docs?

2021-03-03 10:45 UTC, johanstokking commented
> It looks much cleaner as the left side menu expands, preventing the text from wrapping. Give it one last look and see what you think.

I find it too small. It's so small that it becomes annoying to read and to navigate.

Also comparing it to your reference, it's much smaller:

<img width="518" alt="Screenshot 2021-03-03 at 11 45 02" src="https://user-images.githubusercontent.com/13334001/109794234-f1ee0f00-7c15-11eb-8328-469279fa1cdb.png">

2021-03-03 15:07 UTC, pierrephz commented on doc/assets/css/common/variables.scss
> +$red: #FF5C5C;
- for body text: use `$graphite` (rn we are using `$gray`)
- $blue-secondary is: #3D73FF

2021-03-03 15:13 UTC, benolayinka commented
> > It looks much cleaner as the left side menu expands, preventing the text from wrapping. Give it one last look and see what you think.
> 
> I find it too small. It's so small that it becomes annoying to read and to navigate.
> 
> We have enough horizontal space to make the menu on the left wider.
> 
> Also comparing it to your reference, it's much smaller:
> 
> <img alt="Screenshot 2021-03-03 at 11 45 02" width="518" src="https://user-images.githubusercontent.com/13334001/109794234-f1ee0f00-7c15-11eb-8328-469279fa1cdb.png">

Okay. I changed it back, and made the left sidebar slightly larger on screens up to bulma's widescreen query (1200px):

<img width="716" alt="Bildschirmfoto 2021-03-03 um 17 12 12" src="https://user-images.githubusercontent.com/6963436/109826637-a94d4a80-7c43-11eb-931f-20902b653a43.png">

Above 1200px there's enough space available that it looks alright:

<img width="782" alt="Bildschirmfoto 2021-03-03 um 17 12 19" src="https://user-images.githubusercontent.com/6963436/109826748-c6821900-7c43-11eb-85b0-7ce74dc6cf31.png">

2021-03-04 10:22 UTC, johanstokking requested changes
Font size is OK for me now

I didn't look at the code because frontend tech is not my cup of tea.

I do see many content changes; it seems like this is not properly rebased. Holding merge until that is fixed.

2021-03-04 11:12 UTC, pierrephz approved these changes

2021-03-04 13:36 UTC, johanstokking commented
I still don't really get the diff here. Why https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/223/files#diff-44ee0dd4f3e20fbaa46ca55af60ab936cf350b868944abbe0882f8079c5d77b2? Is that part of this PR really?

2021-03-04 13:47 UTC, benolayinka commented
> I still don't really get the diff here. Why https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/223/files#diff-44ee0dd4f3e20fbaa46ca55af60ab936cf350b868944abbe0882f8079c5d77b2? Is that part of this PR really?

Editorconfig changes are re this review comment - https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/223#discussion_r582703568

Codeowner change is re https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/223#pullrequestreview-598549976

2021-03-04 13:50 UTC, benolayinka commented
> I still don't really get the diff here. Why https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/223/files#diff-44ee0dd4f3e20fbaa46ca55af60ab936cf350b868944abbe0882f8079c5d77b2? Is that part of this PR really?

Ah sorry, the anchor link didn't show for me at first. The changes to the cloud integrations are re: TODO :

`Make maximum depth 2 (fix cloud integrations) - let's go through and condense instructions which need to be followed in order in to one page, the cloud integrations are a perfect example. I've done it for Akenza as an example. @nejraselimovic`

Changing arbitrary depth sections in to maximum depth 2, taking advantage of the right side TOC instead of splitting pages in to separate subsections.

2021-03-04 14:02 UTC, johanstokking approved these changes
OK great stuff.

I'm assuming that you checked that links are changed because of the files being moved, that `aliases` are set

2021-03-05 11:22 UTC, adriansmares approved these changes

2021-03-08 09:46 UTC, neoaggelos approved these changes

2021-03-08 10:01 UTC, htdvisser approved these changes

2021-03-08 10:45 UTC, merged