doc: Add mlinux gateway guide
TheThingsIndustries/lorawan-stack-docs pull request #24
Opened 2020-10-07 11:46 UTC by benolayinka

#### Summary

Add multitech mLinux gateway guide

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in `README.md`.
- [x] Style Guidelines: Documentation obeys style guidelines in `README.md`.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-11-10 09:27 UTC, laurensslats requested changes
Why don't you merge it with the Multitech AEP page?

I'd suggest to have 1 page "Multitech Conduit" and 2 sub-page:
Conduit mLinux
Conduit AEP

2020-11-10 09:27 UTC, laurensslats commented on doc/content/gateways/multitechconduit-mlinux/_index.md
> +> **Warning:** The manual configuration of the frequency plan - required to make it work on the The Things (Enterprise) Stack - may result in a mismatch for some of the frequency bands used for the M
```suggestion
> **Warning:** The manual configuration of the frequency plan - required to make it work on the The Things Stack - may result in a mismatch for some of the frequency bands used for the Multitech Gateway.
```

2020-11-10 09:27 UTC, laurensslats commented on doc/content/gateways/multitechconduit-mlinux/_index.md
> +The Gateway Configuration Server can be used to generate a proper `global_conf.json` configuration file for your gateway. You will need a Gateway API key with the `View gateway information` right ena
```suggestion
The Gateway Configuration Server can be used to generate a proper `global_conf.json` configuration file for your gateway. You will need a Gateway API key with the `View gateway information` right enabled. The instructions for creating the API key can be found in the [Adding Gateways]({{< ref "/gateways/adding-gateways" >}}) guide.
```

2020-11-10 09:27 UTC, laurensslats commented on doc/content/gateways/multitechconduit-mlinux/_index.md
> +Make sure you replace `thethings.example.com` with your server address:
```suggestion
Make sure you replace `thethings.example.com` with your server address and `{GATEWAY_ID}` with your Gateway ID.
```

2020-11-10 09:27 UTC, laurensslats commented on doc/content/gateways/multitechconduit-mlinux/_index.md
> +
Can we add the instructions (or reference) for downloading the global_conf.json file from the console?

2020-11-17 12:48 UTC, benolayinka commented
> Why don't you merge it with the Multitech AEP page?
> 
> I'd suggest to have 1 page "Multitech Conduit" and 2 sub-page:
> Conduit mLinux
> Conduit AEP

Because it will break documentation formatting if every gateway has depth 1, but multitech has depth 2 with two sub gateways

2020-11-19 08:13 UTC, htdvisser commented
I think this one had a bit of a bad rebase or something. I can't imagine there need to be so many changes to add an mlinux gateway guide.

2020-11-19 10:02 UTC, laurensslats commented
> I think this one had a bit of a bad rebase or something. I can't imagine there need to be so many changes to add an mlinux gateway guide.

Yeah, I messed up something. Should be reverted now.

2020-11-19 10:03 UTC, laurensslats commented on doc/content/gateways/multitechconduit-mlinux/_index.md
> +
@benolayinka did you look into this?

2020-11-19 10:03 UTC, laurensslats commented on doc/content/gateways/multitechconduit-mlinux/_index.md
> +Make sure you replace `thethings.example.com` with your server address:
@benolayinka this is also not added yet, right?

2020-11-27 10:30 UTC, laurensslats approved these changes

2020-11-30 14:36 UTC, merged