Doc/update migration doc
TheThingsIndustries/lorawan-stack-docs pull request #263
Opened 2021-03-12 12:21 UTC by ymgupta

#### Summary
Update "Migration of device with session" possibility

#### Changes
Updated warning in `Migrating Active Sessions` section

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2021-03-15 11:53 UTC, ymgupta commented
@benolayinka please review this minor change. As session migration is not in place yet, this is a bit important to make it clear to customers.

2021-03-18 06:04 UTC, ymgupta commented
@nejraselimovic Could you please review and suggest necessary changes here?

2021-03-18 09:31 UTC, nejraselimovic requested changes

2021-03-18 09:31 UTC, nejraselimovic commented on doc/content/getting-started/migrating/migrating-from-v2.md
> +{{< warning >}} Migrating device sessions is currently not possible, and is in the pipeline. It will be available in future releases.{{</ warning >}}
```suggestion
{{< warning >}} Migrating device sessions will be available in {{% tts %}} `v3.12` release. {{</ warning >}}
```

2021-03-18 15:33 UTC, nejraselimovic approved these changes

2021-03-20 05:28 UTC, merged