Add mokosmart LoRaWAN Gateway  MKGW2-LW by allen
TheThingsIndustries/lorawan-stack-docs pull request #273
Opened 2021-03-22 11:26 UTC by Fakerallen

#### Summary

Add mokosmart LoRaWAN Gateway  MKGW2-LW by allen

#### Screenshots

...

#### Changes

- ..Add mokosmart LoRaWAN Gateway  MKGW2-LW
- ...

#### Notes for Reviewers

...

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2021-03-30 14:15 UTC, benolayinka commented
Hey @Fakerallen , this document contains all references to Cisco's gateway. Did you mean to update those references?

2021-03-31 01:36 UTC, Fakerallen commented
> Hey @Fakerallen , this document contains all references to Cisco's gateway. Did you mean to update those references?

NO, i just wan to add our gateway , our company  name is mokosmart.

2021-03-31 08:21 UTC, Fakerallen commented
> Hey @Fakerallen , this document contains all references to Cisco's gateway. Did you mean to update those references?

@benolayinka i already change the content ,pls help to check ,thanks.

2021-04-20 07:26 UTC, benolayinka requested changes

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +MOKO 8 channels gateway MKGW2 is based on LoRaWAN protocol, which is embedded with Semtech’s high performance multi-channel transceiver SX1301/SX1257 and MTK platform. It is for
```suggestion
MOKOSMART's 8 channel MKGW2 gateway is embedded with Semtech’s high performance multi-channel transceiver SX1301/SX1257 and MTK platform. It is for indoor use and is easy to install.
```

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +indoor use and easy for installation.
```suggestion
```

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +2. MOKOSMART MKGW2-LW connected to the internet via ethernet or WIFI.（For the ethernet and wifi setting, you can refer to the  5.login into the Gateway and 6.Internet Setting of the user maunal)
```suggestion
2. MOKOSMART MKGW2-LW connected to the internet via Ethernet or WiFi. (For Ethernet and WiFi settings, see sections 5 and 6 of the [user manual](https://www.mokosmart.com/lorawan-gateway-mkgw2-lw/))
```

I couldn't find a link to your user manual online, please update this.

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +## Configuration via Browser
Add newline after heading

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +1. Turn On the gateway and waiting for about 60s.
```suggestion
1. Turn on the gateway and wait for about 60s.
```

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +2. Using your PC or phone connect the SSID of the gateway. The default SSID format is "MKGW2-LW-xxxx” such as " MKGW2-LW-91D8 ", “91D8” is the last two bytes of the gateway MAC address. verify the pa
```suggestion
2. Using your PC or phone, enter the URL of the gateway in a browser. The default URL format is "MKGW2-LW-xxxx”, e.g "MKGW2-LW-91D8 ", where “91D8” is the last two bytes of the gateway MAC address. The default password is Moko4321.
```

This does not look like a valid url. Are you sure it's just "http://MKGW2-LW-xxxx" ?

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +2. Using your PC or phone connect the SSID of the gateway. The default SSID format is "MKGW2-LW-xxxx” such as " MKGW2-LW-91D8 ", “91D8” is the last two bytes of the gateway MAC address. verify the pa
Ahhh I misunderstood, this is the wireless SSID. Ignore my last comment.

```suggestion
2. Using your PC or phone, connect to the WiFi Access Point exposed by the gateway. The default SSID format is "MKGW2-LW-xxxx”, e.g "MKGW2-LW-91D8 ", where “91D8” is the last two bytes of the gateway MAC address. The default password is Moko4321.
```

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +4. Log on using the following default credentials, Username: Admin Password: admin
```suggestion
4. Login using the following default credentials:
- Username: Admin
- Password: admin
```

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +The MOKOSMART MKGW2-LW  support  UDP packet forwarder. Please follow instructions for connecting the MKGW2-LW with UDP packet forwarder.After completing basic configuration, turn to server address in
```suggestion
The MOKOSMART MKGW2-LW supports the UDP packet forwarder. Please follow instructions for connecting the [UDP packet forwarder]({{< ref "gateways/semtech-udp-packet-forwarder" >}}).
```

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +Edit the server parameters:
```suggestion
```

The server settings are all in the UDP Packet Forwarder doc. Remove them here, in case they are updated in the future.

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +- **server_address**: Address of the Gateway Server. If you followed the [Getting Started guide]({{< ref "/getting-started" >}}) this is the same as what you use instead of `thethings.example.com`.
```suggestion
```

Remove these

2021-04-20 07:26 UTC, benolayinka commented on doc/content/gateways/moko-mkgw2-lw/_index.md
> +Don't foget to click "SAVE&APPLY" after you  fill in the parameters.More information and setting, you can refer to the user manual fo mkgw2-lw from moko sales or send email to support_lora@mokotechno
```suggestion
Don't forget to click "SAVE&APPLY" after you fill in the parameters. After a few seconds, your gateway should connect to {{% tts %}}.

For more information, you can refer to the MKGW2-LW user manual or send an email to [support_lora@mokotechnology.com](mailto:support_lora@mokotechnology.com).
```

2021-04-23 01:59 UTC, closed without merging