Make container wider
TheThingsIndustries/lorawan-stack-docs pull request #279
Opened 2021-03-23 17:29 UTC by johanstokking

#### Summary

This makes the rendered content wider.

I found it increasingly annoying to read things as the content was fixed to max 1344px. I have a 4K screen to use more effective screen space and avoid dense content, but our docs doesn't let me do that.

#### Screenshots

Here's what it looks like:

![IMG_4185](https://user-images.githubusercontent.com/13334001/112190905-bf787600-8c05-11eb-805f-1b1081fa1c54.jpg)

#### Changes

Change the default max that Bulma uses from 1344 to 1920px, and the other widths accordingly with the same factor. The widths are still divisible by 12 and 16 for the grid system (that we don't seem to use really).

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2021-03-24 05:55 UTC, benolayinka commented
If this looks good to you I'm good with it, I borrowed the styling from https://doks.netlify.app. I looked at some other examples and it seems like everyone does something different.

<img width="1236" alt="Bildschirmfoto 2021-03-24 um 06 49 40" src="https://user-images.githubusercontent.com/6963436/112262384-dc489400-8c6d-11eb-8751-4e154887e4e6.png">
<img width="1230" alt="Bildschirmfoto 2021-03-24 um 06 49 23" src="https://user-images.githubusercontent.com/6963436/112262409-e7032900-8c6d-11eb-84b4-67787b35c593.png">
<img width="1233" alt="Bildschirmfoto 2021-03-24 um 06 49 13" src="https://user-images.githubusercontent.com/6963436/112262415-e8ccec80-8c6d-11eb-8a91-f3ffae96fc3d.png">
<img width="1216" alt="Bildschirmfoto 2021-03-24 um 06 48 54" src="https://user-images.githubusercontent.com/6963436/112262417-e9658300-8c6d-11eb-8f5b-26df3a6c99c8.png">

2021-03-24 05:56 UTC, benolayinka approved these changes

2021-03-24 09:13 UTC, johanstokking commented
Regarding the comparisons;

- GitHub; let's compare docs with docs. Their docs are full width: https://docs.github.com/en
- Netlify Doks; they have little and less dense content
- Bulma; is full width
- Google; that ain't documentation. See https://developers.google.com/maps/documentation/ios-sdk/overview; menu aligned left, content centered and medium wide (936 px). Note that our content was max 820px

I would prefer the GitHub and Bulma docs design. That is, not centering anything but use the full horizontal screen space and respect the browser window size that the user has chosen. This is, however, more of a quickfix.

2021-03-24 16:48 UTC, kschiffer commented
I agree the current layout is a bit narrow but 1920 is too wide IMO. I prefer a more dense layout, especially for websites with a lot of text (like our docs). In terms of legibility, a line of text should optimally have around 10-16 words, with more than that it becomes hard to find the correct next line when the eye jumps after finishing the line. You can see pretty well how this becomes a problem with the line-lengths in your second screenshot. To compensate, we could make the font-sizes responsive as well but then this whole thing is definitely not a quickfix anymore.

Let's try something a bit smaller like 1600. I don't have the column setup in front of me right now, but it is likely possible to use different responsive classes for it to additionally make it a bit wider in bigger screensizes.

2021-03-24 16:52 UTC, kschiffer requested changes
See above.

2021-03-25 08:38 UTC, johanstokking commented
Looping in some developers to shed some light on @kschiffer's comment:

> I prefer a more dense layout, especially for websites with a lot of text (like our docs). In terms of legibility, a line of text should optimally have around 10-16 words, with more than that it becomes hard to find the correct next line when the eye jumps after finishing the line

I personally disagree with this. The audience for documentation are typically technical people, and we should respect their window size. If they think that the lines are too long, they just resize the window. We should not have an attitude towards them that we know better.

2021-03-25 08:39 UTC, KrishnaIyer approved these changes
Looks nicer with the wider content. I also agree that the original layout was way too narrow and nothing could be done about it.

2021-03-25 08:44 UTC, johanstokking commented
For illustration, all green areas are a waste of space, while the rest is so crammed together that it becomes hard to read:

![thethingsindustries com_docs_integrations_aws-iot_default_deployment-guide_ (1)](https://user-images.githubusercontent.com/13334001/112444729-a62f1100-8d4e-11eb-8b39-9cae79f44f58.png)

2021-03-25 09:21 UTC, johanstokking commented
Made a few minor tweaks with the columns.

Here's a video of how it looks responsively.

https://user-images.githubusercontent.com/13334001/112449425-a7167180-8d53-11eb-90c4-a9ab02aac2ac.mov

2021-03-25 09:57 UTC, adriansmares approved these changes
I prefer the wider container. I consider that people with larger screen sizes, myself included, prefer having more content available on the screen.

2021-03-25 10:10 UTC, htdvisser commented
I'm with @kschiffer on this one. I also experience that when lines are longer, the text becomes more difficult to read. 

We want our documentation to be easy to read for everyone. We want to encourage people to actually read it instead of just skimming over the page. That's why we prefer text over bullet lists, and also why we should optimize our styling for readability according to best practices. @kschiffer is our UI/UX expert, so I think that we should follow his suggestions when in doubt.

In the end I guess it's mostly about personal preference. I like to use a 27 inch HiDPI screen at a resolution that looks like 2560x1440, I like my windows full-screen, I like the main content in the middle of the window, with line length of 120 characters. The rest of the screen can be filled with sidebars, although I also sometimes like to use "distraction-free" or "zen" mode.

So while I think that it's definitely a good idea to make better use of the space by increasing the width of the sidebars, I don't think we should increase the width of the main content.

2021-03-25 12:08 UTC, johanstokking commented
> So while I think that it's definitely a good idea to make better use of the space by increasing the width of the sidebars, I don't think we should increase the width of the main content.

Can you checkout this branch and run `make server` and see what you think?

2021-03-25 12:29 UTC, htdvisser commented
The first thing I notice is that the page isn't centered properly; I had to move a bit to the right to be "in front" of it. When opening up the inspector you can also see that the right sidebar is pushed out of the container:

<img width="2560" alt="Screen Shot 2021-03-25 at 13 16 09" src="https://user-images.githubusercontent.com/181308/112471921-cb327c80-8d6c-11eb-92d3-71f5faab47d7.png">

After clicking around a bit more, it looks like this only happens on some pages, so probably something we should check, because other pages look fine:

<img width="2560" alt="Screen Shot 2021-03-25 at 13 22 29" src="https://user-images.githubusercontent.com/181308/112472310-43993d80-8d6d-11eb-9c74-22e79ae58922.png">

I do still think that the text lines are too long at the largest breakpoint, but at the smaller breakpoint I think it's acceptable:

<img width="1706" alt="Screen Shot 2021-03-25 at 13 25 21" src="https://user-images.githubusercontent.com/181308/112472896-f4074180-8d6d-11eb-93aa-7a591d278264.png">

2021-03-25 13:20 UTC, johanstokking commented
> After clicking around a bit more, it looks like this only happens on some pages, so probably something we should check

That is because of things like `GET /api/v3/applications/{application_ids.application_id}/collaborator/organization/{collaborator.organization_ids.organization_id}` in a table cell. Not sure if we can automatically cut those with css, but we probably can.

---

Did an additional tweak.

2021-03-26 08:04 UTC, htdvisser approved these changes

2021-03-26 10:05 UTC, johanstokking commented
@kschiffer I value your opinion here, can you have another look, ideally by running locally?

2021-03-26 12:12 UTC, kschiffer approved these changes
Yes, thank you. This is what I asked for. The distribution of the columns is improved now, so that the content column is not becoming too wide, while the formerly narrow navigation columns get more space now.

2021-03-26 12:40 UTC, merged