doc: Update troubleshooting
TheThingsIndustries/lorawan-stack-docs pull request #297
Opened 2021-03-31 15:10 UTC by nejraselimovic

#### Summary
Update troubleshooting with this error:
![image](https://user-images.githubusercontent.com/65215579/113167331-ebb67700-9243-11eb-83e9-e74fa7883896.png)

#### Checklist
- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2021-04-02 12:44 UTC, kschiffer requested changes

2021-04-02 12:44 UTC, kschiffer commented on doc/content/getting-started/installation/troubleshooting.md
> +Make sure you used the same `client-secret` in your {{% tts %}} configuration (`ttn-lw-stack-docker.yml` file) and for authorizing the console client in [Running {{% tts %}}]({{< relref "running-the-
```suggestion
If you see an error reading 

> The client is not authorized to request a token using this method

when trying to log into the Console, make sure you used the same `client-secret` in your {{% tts %}} configuration (`ttn-lw-stack-docker.yml` file) and for authorizing the Console client in [Running {{% tts %}}]({{< relref "running-the-stack" >}}).
```

2021-04-06 07:25 UTC, neoaggelos approved these changes

2021-04-06 11:56 UTC, kschiffer approved these changes

2021-04-06 14:02 UTC, merged