Replace Lato with Inter font
TheThingsIndustries/lorawan-stack-docs pull request #324
Opened 2021-04-28 09:00 UTC by benolayinka

#### Summary

Closes #252 

#### Screenshots

<img width="1400" alt="Bildschirmfoto 2021-04-28 um 14 44 36" src="https://user-images.githubusercontent.com/6963436/116376748-44236900-a830-11eb-97ae-a9f4db913c7c.png">

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2021-04-28 09:03 UTC, pierrephz approved these changes

2021-04-28 09:10 UTC, kschiffer requested changes
See my remark.

2021-04-28 09:10 UTC, kschiffer commented on doc/assets/css/common/fonts.scss
> +@import url('https://fonts.googleapis.com/css?family=Inter:400,700&display=swap');
Please use add the font as an asset and then load it locally. We want to avoid unnecessary requests to google if we can.

2021-04-30 12:00 UTC, kschiffer approved these changes

2021-05-03 11:17 UTC, merged