Mark application server linking as removed
TheThingsIndustries/lorawan-stack-docs pull request #41
Opened 2020-10-16 15:35 UTC by adriansmares

#### Summary

References https://github.com/TheThingsNetwork/lorawan-stack/issues/2312
References https://github.com/TheThingsNetwork/lorawan-stack/pull/3263

#### Changes

- Add `Removed in version` shortcode
- Mark linking sections as removed in v3.10

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`
- [x] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2020-10-19 07:31 UTC, htdvisser approved these changes

2020-10-19 09:22 UTC, johanstokking commented
This is not landing in 3.10, is it?

2020-10-19 09:36 UTC, htdvisser requested changes
You're right. Let's change this to `v3.11`.

2020-10-20 12:29 UTC, kschiffer approved these changes

2020-10-20 14:34 UTC, benolayinka approved these changes

2020-10-21 08:26 UTC, htdvisser commented
Blocked on https://github.com/TheThingsNetwork/lorawan-stack/issues/2312 and https://github.com/TheThingsNetwork/lorawan-stack/pull/3263

2020-11-30 07:57 UTC, johanstokking approved these changes

2020-11-30 08:33 UTC, htdvisser approved these changes

2020-11-30 08:50 UTC, pierrephz approved these changes

2020-12-01 13:05 UTC, merged