Add EC5 warning to payload formatter doc
TheThingsIndustries/lorawan-stack-docs pull request #68
Opened 2020-11-05 11:51 UTC by benolayinka

#### Summary

Warn about EC5 vs EC6

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Run Locally: Verified that the docs build using `make server`
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2020-11-05 12:02 UTC, kschiffer requested changes
Note that it's called ES5, not EC5.

2020-11-05 12:02 UTC, kschiffer commented on doc/content/integrations/payload-formatters/javascript.md
> +> **Note:** There are major differences between EC5 and EC6. See [here](https://www.javatpoint.com/es5-vs-es6) for a quick comparison. Notably, `let`, `const`, and arrow functions are not supported b
```suggestion
> **Note:** Payload formatters use ECMAScript ES5 (2015), which has some distinct differences compared to newer, commonly used ECMAScript revisions. See [here](https://www.javatpoint.com/es5-vs-es6) for a quick comparison. Notably, `let`, `const`, and arrow functions are not supported by ES5.
```

2020-11-05 12:07 UTC, kschiffer approved these changes

2020-11-06 06:45 UTC, johanstokking approved these changes

2020-11-06 10:54 UTC, adriansmares approved these changes

2020-11-09 14:47 UTC, merged