doc: Add CH eu2 cluster info
TheThingsIndustries/lorawan-stack-docs pull request #701
Opened 2021-12-29 18:17 UTC by nejraselimovic

#### Summary
Closes #691 

#### Checklist
- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2021-12-30 07:44 UTC, htdvisser requested changes

2021-12-30 07:44 UTC, htdvisser commented on doc/themes/the-things-stack/layouts/shortcodes/cluster-selector.html
> +        <option value="eu2">Europe 2 (UK)</option>
```suggestion
```

Only The Things Stack Cloud has an `eu2` cluster. The Things Stack Community Edition doesn't.

2022-01-03 07:58 UTC, htdvisser approved these changes

2022-01-03 13:43 UTC, kschiffer approved these changes

2022-01-05 10:24 UTC, merged