Update gateway onboarding docs
TheThingsIndustries/lorawan-stack-docs pull request #914
Opened 2022-07-11 12:46 UTC by mjamescompton

#### Summary

References https://github.com/TheThingsNetwork/lorawan-stack/issues/3947

#### Screenshots

<img width="916" alt="Screenshot 2022-07-11 at 14 36 11" src="https://user-images.githubusercontent.com/46600603/178265687-514cfa7f-66b2-4214-8d6a-1aea5e843068.png">
<img width="919" alt="Screenshot 2022-07-11 at 14 36 16" src="https://user-images.githubusercontent.com/46600603/178265693-caaab544-164a-4aa9-b022-67723d3bedef.png">
<img width="958" alt="Screenshot 2022-07-11 at 14 36 22" src="https://user-images.githubusercontent.com/46600603/178265700-9669d840-5b64-40af-8508-75bab5d3aa0a.png">

Image optimisation

<img width="1007" alt="Screenshot 2022-07-11 at 14 32 37" src="https://user-images.githubusercontent.com/46600603/178265711-35ce0dce-8001-4752-8991-3b3463ad67bd.png">

#### Changes

- Extend the current docs to include claiming option.
- Remove out of date video and related text.
- Optimise all the gateway related images.

#### Notes for Reviewers

@benolayinka Not sure what your process is for making the videos but if you have time you can create a new one via your local if you run the PR https://github.com/TheThingsIndustries/lorawan-stack/pull/3304 . I still need it approved so it may change so I'll leave it up to you weather you want to wait until this is live to update the video docs.

Also I will wait until pr is approved to merge.

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2022-08-23 16:04 UTC, kschiffer requested changes
Thanks for this

2022-08-23 16:04 UTC, kschiffer commented on doc/content/gateways/adding-gateways/_index.md
> +{{< note >}}Claiming may not be possible on your version of The Thing Stack, if not you will see the manual registration form by default.{{</ note >}}
```suggestion
{{< note >}}Claiming of gateways is not supported on {{% tts %}} Open Source. In that case, you will see the manual registration form by default.{{</ note >}}
```

2022-08-23 16:04 UTC, kschiffer commented on doc/content/gateways/adding-gateways/_index.md
> +Depending of weather the **Gateway EUI** is claimable you will either be shown the claiming form or the manual registration form.
```suggestion
Depending on whether the **Gateway EUI** is claimable you will either be shown the claiming form or the manual registration form.
```

2022-08-23 16:04 UTC, kschiffer commented on doc/content/gateways/adding-gateways/_index.md
> +On claiming form fill in the **Authentication Code**, **Gateway ID** and the **Frequency Plan**. Click **Claim Gateway** to finish.
```suggestion
If your gateway is claimable (e.g. The Things Indoor Gateway), you will see the claiming form. Here, fill in the **Authentication Code**, **Gateway ID** and the **Frequency Plan**. Click **Claim Gateway** to finish.
```

2022-08-23 16:04 UTC, kschiffer commented on doc/content/gateways/adding-gateways/_index.md
> +Fill the **Gateway EUI** and click **Confirm** or **Continue without EUI**.
```suggestion
Fill the **Gateway EUI** and click **Confirm**. Some gateways do not use a **Gateway EUI** (e.g. The Things Kickstarter Gateway), in which case you can just click on **Continue without EUI**.
```

2022-08-29 09:13 UTC, kschiffer approved these changes

2022-08-31 09:55 UTC, KrishnaIyer approved these changes
Nice!

2022-09-01 09:06 UTC, merged